<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfI4kwb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfI4kwb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfI4kwb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfI4kwb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDfI4kwb\App_KernelDevDebugContainer([
    'container.build_hash' => 'DfI4kwb',
    'container.build_id' => '9aad95e7',
    'container.build_time' => 1671196079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfI4kwb');
