<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4hxJaR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4hxJaR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4hxJaR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4hxJaR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4hxJaR\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4hxJaR',
    'container.build_id' => '6c27b114',
    'container.build_time' => 1671027169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4hxJaR');
