<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3jRw4TS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3jRw4TS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3jRw4TS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3jRw4TS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3jRw4TS\App_KernelDevDebugContainer([
    'container.build_hash' => '3jRw4TS',
    'container.build_id' => '83b11900',
    'container.build_time' => 1671025984,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3jRw4TS');
